### ISSUE TITLE
PDFParser failure

### ISSUE THREAD

**Issue by doppioandante** [galkahana/PDFWriterSamples#2]
Hi, I'm trying to use the parser example.
(note: ePDFObjectArray should be PDFObject::ePDFObjectArray I suppose)

I'm trying to parse the following file from https://blog.idrsolutions.com/2010/10/make-your-own-pdf-file-part-4-hello-world-pdf/

``` pdf
%PDF-1.4
1 0 obj <</Type /Catalog /Pages 2 0 R>>
endobj
2 0 obj <</Type /Pages /Kids [3 0 R] /Count 1>>
endobj
3 0 obj<</Type /Page /Parent 2 0 R /Resources 4 0 R /MediaBox [0 0 500 800] /Contents 6 0 R>>
endobj
4 0 obj<</Font <</F1 5 0 R>>>>
endobj
5 0 obj<</Type /Font /Subtype /Type1 /BaseFont /Helvetica>>
endobj
6 0 obj
<</Length 44>>
stream
BT /F1 24 Tf 175 720 Td (Hello World!)Tj ET
endstream
endobj
xref
0 7
0000000000 65535 f
0000000009 00000 n
0000000056 00000 n
0000000111 00000 n
0000000212 00000 n
0000000250 00000 n
0000000317 00000 n
trailer <</Size 7/Root 1 0 R>>
startxref
406
%%EOF
```

It fails without telling much on what the error is, any hint?

**Comment by galkahana** [comment]
If you did like me, and copied the text into a PDF file, then you get a PDF file where the positions are all wrong.
They are wrong because line endings are counted as 1 character for the sake of how the xref here counts positions and how its position is calculated, but are actually two characters.
correct the xref and it should be fine.

here is the correct file trailer:
xref
0 7
0000000000 65535 f
0000000010 00000 n
0000000059 00000 n
0000000116 00000 n
0000000219 00000 n
0000000259 00000 n
0000000328 00000 n
trailer <</Size 7/Root 1 0 R>>
startxref
425
%%EOF

**Comment by doppioandante** [comment]
Thanks, I didn't realize that.
